### ISSUE TITLE
Style improvements for column-config and angular theming support

### ISSUE THREAD

**Issue by Lotec724** [pgerke/ngx-mat-table-multi-sort#37]
Hello,
first of all, thank you for starting this project! I'm a user and contributor for the ngx-mat-multi-sort project, so I welcome your effort to improve on that solution.

I just checked out the latest version (19.2.0) and noticed some issues with the current implementation of the column visibility and order configuration. 
1. When I drag a column, the preview has a scrollbar for the table-column item. This in turn creates a line break with "Join Date" for example.
2. During dragging, the placeholder is not hidden, so it appears twice.
3. The drag preview has a transparent background, so it overlaps with the elements behind, which makes it a bit confusing.

I also noticed that the overlay is currently styled with explicit colors. I think it would be great if we could support dark mode via material theming out of the box. 

So I propose the following changes to `mat-table-column-config.component.scss`:

```scss
// modify
.table-column-list {
  padding: 0.375rem; // I think this is unnecessary on the list container itself, but that is a matter of preference 
  background-color: var(--mat-sys-surface-container, #eee); // providing a fallback color if no material theme is defined
  color: var(--mat-sys-on-surface, rgba(0, 0, 0, 0.87));
}

.table-column {
  background: var(--mat-sys-surface, #fff); // fixes the overlap
}

// add these classes
.cdk-drag-preview {
  border: none;
  box-sizing: border-box;
  border-radius: 4px;
  box-shadow: 0 5px 5px -3px rgba(0, 0, 0, 0.2),
  0 8px 10px 1px rgba(0, 0, 0, 0.14),
  0 3px 14px 2px rgba(0, 0, 0, 0.12);
}

.cdk-drag-placeholder {
  opacity: 0; // hide the placeholder
}

.cdk-drag-animating {
  transition: transform 250ms cubic-bezier(0, 0, 0.2, 1);
}

.cdk-drop-list-dragging .table-column:not(.cdk-drag-placeholder) {
  transition: transform 250ms cubic-bezier(0, 0, 0.2, 1);
}
```
Most of these are taken straight from the https://material.angular.io/cdk/drag-drop/overview examples and are implemented in a similar way in `mat-multi-sort-header.component.scss`.

Since angular changed the theming with v19, I think it would be a good idea to remove the prebuilt indigo theme (in `angular.json`) for the demo and style the application from `styles.scss` instead. For testing purposes I added the following:
```scss
@use '@angular/material' as mat;

html {
  color-scheme: light dark;
  @include mat.theme((
    color: (
      primary: mat.$azure-palette,
      tertiary: mat.$blue-palette
    ),
    typography: Roboto,
    density: 0
  ))
}
```
This causes the theme to change based on the user OS preferences. You also need to provide the font in the index.html by adding the following to the `<head>`:
```html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">
```

This change would of course have effects on the other components as well, but makes the library as a whole work with the standard theming mechanism. The end result is something like this:
![image](https://github.com/user-attachments/assets/4c76f91c-ad08-41bb-a740-6df2e1704c2c)

Let me know what you think about these changes and if you need a PR.
